import fs from 'node:fs';
import path from 'node:path';
import PDFDocument from 'pdfkit';
import { env, ensureStorageDir } from '../config/env.js';
import { buildPdfPath } from '../utils/pdf.js';

const pdfDir = ensureStorageDir(path.resolve('server/storage/pdfs'));

function writePdfFile(filename, lines) {
  const filePath = buildPdfPath(pdfDir, filename);
  const doc = new PDFDocument({ margin: 40 });
  const stream = fs.createWriteStream(filePath);

  doc.pipe(stream);
  lines.forEach((line) => doc.text(line));
  doc.end();

  return filePath;
}

import { store } from '../data/store.js';

export function generateInvoicePdf(invoice) {
  const customer = (store.customers || []).find((c) => c.id === invoice.customerId) || {};

  const lines = [
    `NxtBiz Invoice: #${invoice.id}`,
    `Status: ${invoice.status || 'draft'}`,
    `Due Date: ${invoice.dueDate ? new Date(invoice.dueDate).toLocaleDateString() : 'Unassigned'}`,
    '',
    'Billing Details:',
    `  - Customer: ${customer.name || 'Unknown'}`,
    `  - Email: ${customer.email || 'N/A'}`,
    `  - Company: ${customer.company || 'N/A'}`,
    '',
    'Line Items:',
  ];

  const items = invoice.lineItems || [];
  if (items.length > 0) {
    items.forEach((item, index) => {
      const sub = (item.quantity || 1) * (item.unitPrice || 0);
      lines.push(`  ${index + 1}. ${item.description} - Qty: ${item.quantity} - Price: $${item.unitPrice} - Subtotal: $${sub}`);
    });
  } else {
    lines.push(`  - Base Invoice Fee: $${invoice.amount || 0}`);
  }

  lines.push('');
  lines.push(`Subtotal: $${invoice.amount || 0}`);
  lines.push('Tax (0.00%): $0.00');
  lines.push(`Total Amount Due: $${invoice.amount || 0}`);
  lines.push('');
  lines.push('Generated by NxtBiz');

  const filePath = writePdfFile(`invoice-${invoice.id}`, lines);
  return `${env.pdfBaseUrl}/${path.basename(filePath)}`;
}

export function generateReportPdf(report) {
  const lines = [
    `NxtBiz Report: ${report.title || report.id}`,
    `Type: ${report.type || 'Executive'}`,
    `Date: ${new Date().toLocaleDateString()}`,
    `Generated By: User #${report.generatedBy || 'System'}`,
    '',
    `Summary: ${report.summary || 'No summary provided'}`,
    '',
    'Metrics Overview:',
  ];

  if (report.metrics) {
    const m = report.metrics;
    lines.push(`  - Customer Satisfaction: ${m.customerSatisfaction || 0}%`);
    lines.push(`  - Response Time Score: ${m.responseTime || 0}%`);
    lines.push(`  - Invoice Collection Ratio: ${m.invoiceCollection || 0}%`);
    lines.push(`  - Ticket Resolution Ratio: ${m.ticketResolution || 0}%`);
    lines.push(`  - Lead Conversion Score: ${m.leadConversion || 0}%`);
    lines.push(`  - Overall Business Health Score: ${m.healthScore || 0}%`);
  } else {
    lines.push('  - No operational metrics recorded');
  }

  lines.push('');
  lines.push('Actionable Recommendations:');
  const recs = Array.isArray(report.recommendations)
    ? report.recommendations
    : typeof report.recommendations === 'string'
    ? report.recommendations.split(',').map((r) => r.trim()).filter(Boolean)
    : [];

  if (recs.length > 0) {
    recs.forEach((rec) => lines.push(`  • ${rec}`));
  } else {
    lines.push('  • No recommendations identified.');
  }

  lines.push('');
  lines.push('Generated by NxtBiz');

  const filePath = writePdfFile(`report-${report.id}`, lines);
  return `${env.pdfBaseUrl}/${path.basename(filePath)}`;
}
